### PR TITLE
Only limit total # args and total arg length

### PR DESCRIPTION
**Pull request by justicz**
This seems more developer friendly as per some feedback we received.

### CODE REVIEW

**Comment by derbear** [comment]
Can I submit a lot of empty-length ApplicationArgs `""`, more than 2048?

**Comment by derbear** [comment]
Also, isn't the maximum transaction size about 1000?

**Comment by justicz** [comment]
- No, because we limit the total number of app arguments to 16
- There isn't an explicitly set max transaction size, I don't think. It's implicit based on the max lengths of each individual field.

**Comment by derbear** [comment]
Oh yeah, I missed that total number of arguments is still 16

**Comment by derbear** [comment]
I think up to now we've been assuming that (unsigned) transactions are around 1K bytes. Does this mean that they can reach around 3K bytes now?

**Pull request merged**
